batch_type: folded
#batch_size: 16
#accum_grad: 6
batch_size: 32
accum_grad: 1
max_epoch: 30
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 1

freeze_param: [
    "encoder.encoders",
]

input_size: 1
encoder: hubert
encoder_conf:
    output_size: 1024
    normalize_before: false
    freeze_finetune_updates: 100000000 # la je met tout pcq le modele est deja FT celui que je vais load donc vrmt je ne vais FT que la prediction head
    hubert_url: https://dl.fbaipublicfiles.com/hubert/hubert_large_ll60k.pt
    hubert_dir_path: ./downloads/hubert_pretrained_models/hubert_large_ll60k.pt
    heads: false
    attention_in_heads: false
    heads_ff_dim: 512
    heads_att_dim: 512
    heads_layer_list: "10_15_20_23"



model_conf:
    ctc_weight: 1.0
    interctc_weight: 0.999999
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0002  
unused_parameters: true

frontend: null

normalize: null

specaug: null # pas de SpecAUG ??? A VERIF avec Xuankai par ex.

init: xavier_uniform