batch_type: folded
batch_size: 16
accum_grad: 2
max_epoch: 100
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

freeze_param: [
    "encoder.encoders.mask_emb", "encoder.encoders.feature_extractor",
    "encoder.encoders.post_extract_proj", "encoder.encoders.encoder.pos_conv",
]

input_size: 1
encoder: hubert
encoder_conf:
    output_size: 256
    normalize_before: false
    freeze_finetune_updates: 20000 # 20000 instead of 10000 because the semi-supervised approach pass twice through the encoder at each step
    # if use espent-trained model
    #hubert_url: espnet
    #hubert_dir_path: ../../librispeech/ssl1/exp/pretrain_train_asr_hubert_base_960h_pretrain_it1_raw_iter1/valid.acc.best.pth
    # if use downloaded model:
    hubert_url: https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt
    hubert_dir_path: ./downloads/hubert_pretrained_models/hubert_base_ls960.pt
    #hubert_url: espnet
    #hubert_dir_path: /projects/tir5/users/dberrebb/fused_pr/espnet/egs2/librispeech/ssl1/continue_107_exp/pretrain_train_asr_hubert_base_960h_pretrain_it2_raw_iter2_freeze/valid.acc.ave_5best.pth
    #hubert_dir_path: /projects/tir5/users/dberrebb/fused_pr/espnet/egs2/librispeech/ssl1/continue_107_exp/pretrain_train_asr_hubert_base_960h_pretrain_it2_freeze_raw_iter2_freeze_all/valid.acc.ave_5best.pth


semi_supervised: true
alpha_ss: 0.5

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.00002
    
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 8000

unused_parameters: true

frontend: null

normalize: null

specaug: null