batch_type: folded
batch_size: 2
accum_grad: 1
max_epoch: 2
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 1

freeze_param: [
    "encoder",
]

input_size: 1
encoder: hubert
encoder_conf:
    output_size: 256
    normalize_before: false
    freeze_finetune_updates: 10000
    # if use espent-trained model
    #hubert_url: espnet
    #hubert_dir_path: ../../librispeech/ssl1/exp/pretrain_train_asr_hubert_base_960h_pretrain_it1_raw_iter1/valid.acc.best.pth
    # if use downloaded model:
    hubert_url: https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt
    hubert_dir_path: ./downloads/hubert_pretrained_models/hubert_base_ls960.pt
    #hubert_url: espnet
    #hubert_dir_path: /projects/tir5/users/dberrebb/fused_pr/espnet/egs2/librispeech/ssl1/continue_107_exp/pretrain_train_asr_hubert_base_960h_pretrain_it2_raw_iter2_/valid.acc.best.pth
    

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0
    
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 8000

unused_parameters: true

frontend: null

normalize: null

specaug: null